# Generated by Django 2.2.1 on 2019-05-31 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Group1', models.CharField(max_length=200)),
                ('Group2', models.CharField(max_length=200)),
                ('Author', models.CharField(max_length=200)),
                ('Reason', models.TextField()),
                ('Place', models.IntegerField(blank=True, choices=[(1, '농구(왼)'), (2, '농구(오)'), (3, '축구'), (4, '풋살'), (5, '배구(왼)'), (6, '배구(오)')], default=1)),
            ],
        ),
    ]
