# Generated by Django 2.2.1 on 2019-06-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0005_reservation_data_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation_data',
            name='Date',
            field=models.DateField(),
        ),
    ]
